# Generated by Django 3.2 on 2021-04-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='enrollment_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
